"""calendar_invites: the durable copy of an invite

Revision ID: 0001_calendar_invites
Revises:
Create Date: 2026-09-20

Hand-written, not autogenerated. This lineage shares a database with
`packages/ears-discord`'s and stamps its own `alembic_version_calendar`;
see `alembic/env.py` for why both of those matter.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "0001_calendar_invites"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSONType = sa.JSON().with_variant(JSONB, "postgresql")


def upgrade() -> None:
    op.create_table(
        "calendar_invites",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agenda", JSONType, nullable=False),
        sa.Column("context", sa.Text(), nullable=False, server_default=""),
        sa.Column("started", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("ears_meeting_id", sa.String(length=64), nullable=True),
        sa.Column("ears_session_id", sa.String(length=64), nullable=True),
        sa.Column("last_state", JSONType, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_calendar_invites")),
    )
    # The scheduler's only query shape: everything not yet started, by start time.
    op.create_index(
        "ix_calendar_invites_started_starts_at",
        "calendar_invites",
        ["started", "starts_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_calendar_invites_started_starts_at", table_name="calendar_invites")
    op.drop_table("calendar_invites")
