"""meetings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 13:03:46.301559
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column(
            "agenda",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.add_column("sessions", sa.Column("meeting_id", sa.Uuid(), nullable=True))
    op.alter_column("sessions", "guild_id", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column("sessions", "channel_id", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.create_foreign_key(
        op.f("fk_sessions_meeting_id_meetings"),
        "sessions",
        "meetings",
        ["meeting_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_sessions_meeting_id_meetings"), "sessions", type_="foreignkey")
    op.alter_column("sessions", "channel_id", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column("sessions", "guild_id", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.drop_column("sessions", "meeting_id")
    op.drop_table("meetings")
    # ### end Alembic commands ###
